eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
  port: ${EUREKA_SERVER_PORT:8761}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
