server:
  port: ${SERVER_PORT:8085}

# Logging configuration
logging:
  level:
    io:
      itpl:
        gateway: TRACE

keycloak:
  realm: ${KEYCLOAK_REALM:magri}
  clientId: ${KEYCLOAK_CLIENT_ID:gateway}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET:JRpC59Bt3FCfBMU8KybPuza4fGAxEVdG}
  urls:
    auth: ${KEYCLOAK_DOMAIN:http://3.71.186.189:8080}

spring:
  data:
    mongodb:
      uri: mongodb+srv://iwant:iwant@iwant-cluster.xc2j1v4.mongodb.net/
      database: gateway
      auto-index-creation: true
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.urls.auth}/realms/${keycloak.realm}
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: ${keycloak.clientId}
            client-secret: ${keycloak.clientSecret}
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${keycloak.urls.auth}/realms/{keycloak.realm}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    prefer-ip-address: true
  port: ${EUREKA_SERVER_PORT:8761}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/

jwt:
  auth:
    converter:
      resource-id: gateway

# Micrometer configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

# URL of different services
system:
  service:
    url : lb://SYSTEM-SERVICE/

product:
  service:
    url : lb://PRODUCT-SERVICE/

sns:
  service:
    url : lb://SNS-SERVICE/

media:
  service:
    url : lb://MEDIA-SERVICE/

order:
  service:
    url : lb://ORDER-SERVICE/

content:
  service:
    url : lb://CONTENT-SERVICE/