server:
  port: ${SERVER_PORT:8082}

# keycloak configuration
keycloak:
  realm: ${KEYCLOAK_REALM:magri}
  clientId: ${KEYCLOAK_CLIENT_ID:system-service}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET:4CoHVVttHY533yBSCGM2dxUoU6RhQUZs}
  urls:
    auth: ${KEYCLOAK_DOMAIN:http://192.168.1.90:8080}

# Auth server and gateway configuration
spring:
  data:
    mongodb:
      uri: mongodb+srv://iwant:iwant@iwant-cluster.xc2j1v4.mongodb.net/
      database: system-service
      auto-index-creation: true
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.urls.auth}/realms/${keycloak.realm}
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: ${keycloak.clientId}
            client-secret: ${keycloak.clientSecret}
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${keycloak.urls.auth}/realms/{keycloak.realm}

# Eureka Configuration
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:service-registry}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

jwt:
  auth:
    converter:
      resource-id: system-service

# OTP configuration
otp:
  otpLength: 6
  otpValidityInSeconds: 300
  otpEncryption: false
  transaction:
    codeLength : 12

# Kafka Configuration
kafka:
  url: localhost:9092

# Micrometer configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
