server:
  port: ${SERVER_PORT:8082}

# keycloak configuration
keycloak:
  realm: ${KEYCLOAK_REALM:magree}
  clientId: ${KEYCLOAK_CLIENT_ID:system-service}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET:8Lsp0X6kln6rGAHYz6jIlbJusu9BTXW5}
  urls:
    auth: ${KEYCLOAK_DOMAIN:http://localhost:8080}

# Auth server and gateway configuration
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: system-service
      auto-index-creation: true
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.urls.auth}/realms/${keycloak.realm}
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: ${keycloak.clientId}
            client-secret: ${keycloak.clientSecret}
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${keycloak.urls.auth}/realms/{keycloak.realm}

# Eureka Configuration
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
  port: ${EUREKA_SERVER_PORT:8761}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/

jwt:
  auth:
    converter:
      resource-id: system-service

# OTP configuration
otp:
  otpLength: 6
  otpValidityInSeconds: 300
  otpEncryption: false
  transaction:
    codeLength : 12


# Kafka Configuration
kakfa:
  url: localhost:9092

# Micrometer configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
#  metrics:
#    export:
#      - type: zipkin
#        uri: http://zipkin:9411/api/v2/spans
#        step: 10s
#        batch: true
#
## Zipkin configuration
#zipkin:
#  sender:
#    type: web
#    url: http://zipkin:9411/api/v2/spans
#
## Brave (Zipkin instrumentation) configuration
#brave:
#  tracing:
#    serviceName: 'gateway'
#    sampler:
#      probability: 1.0
