server:
  port: ${SERVER_PORT:8084}

# keycloak configuration
keycloak:
  realm: ${KEYCLOAK_REALM:magri}
  clientId: ${KEYCLOAK_CLIENT_ID:product-service}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET:4ziYrT8Ke8f1Fd7qCEZxjbxZBWmmfNYQ}
  urls:
    auth: ${KEYCLOAK_DOMAIN:http://136.232.113.214:8080}

# Auth server and gateway configuration
spring:
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.urls.auth}/realms/${keycloak.realm}
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: ${keycloak.clientId}
            client-secret: ${keycloak.clientSecret}
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${keycloak.urls.auth}/realms/{keycloak.realm}

# Eureka Configuration
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
  port: ${EUREKA_SERVER_PORT:8761}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/

jwt:
  auth:
    converter:
      resource-id: product-service

# Micrometer configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
